### ISSUE TITLE
TypeError: Cannot read property '_s' of undefined

### ISSUE THREAD

**Issue by strugee** [e14n/databank-mongodb#6]
I'm trying to set up Pump.io and I get the following error when I load the front page:

```
% journalctl --unit=pump.io | tail -11
Jul 26 04:03:44 steevie pump[22315]: TypeError: Cannot read property '_s' of undefined
Jul 26 04:03:44 steevie pump[22315]: at recToValue (/usr/local/lib/node_modules/databank-mongodb/lib/mongodb.js:170:20)
Jul 26 04:03:44 steevie pump[22315]: at /usr/local/lib/node_modules/databank-mongodb/lib/mongodb.js:333:29
Jul 26 04:03:44 steevie pump[22315]: at handleCallback (/usr/local/lib/node_modules/databank-mongodb/node_modules/mongodb/lib/utils.js:95:12)
Jul 26 04:03:44 steevie pump[22315]: at /usr/local/lib/node_modules/databank-mongodb/node_modules/mongodb/lib/collection.js:564:5
Jul 26 04:03:44 steevie pump[22315]: at executeOp (/usr/local/lib/node_modules/databank-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:376:33)
Jul 26 04:03:44 steevie pump[22315]: at /usr/local/lib/node_modules/databank-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:422:11
Jul 26 04:03:44 steevie pump[22315]: at Callbacks.emit (/usr/local/lib/node_modules/databank-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:95:3)
Jul 26 04:03:44 steevie pump[22315]: at null.messageHandler (/usr/local/lib/node_modules/databank-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:246:23)
Jul 26 04:03:44 steevie pump[22315]: at Socket.<anonymous> (/usr/local/lib/node_modules/databank-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:262:22)
Jul 26 04:03:44 steevie pump[22315]: at Socket.emit (events.js:95:17)
```

Any idea what's going on here? Here's the relevant section of my config file:

```
	"driver":  "mongodb",
	"params":  {
		"host": "localhost",
		"port": 27017,
		"dbname": "pumpio",
		"dbuser": "pump.io",
		"dbpass": "ontEddikdijthewv"
	},
```

Here's my Pump.io version information:

```
% cd /usr/local/lib/node_modules/pump.io; npm ll
pump.io@0.3.0
│ /usr/local/lib/node_modules/pump.io
│ Version 0.3.0
│ git://github.com/e14n/pump.io.git
│ http://pump.io/
├─┬ bcrypt@0.7.8
│ │ A bcrypt library for NodeJS.
│ │ https://github.com/ncb000gt/node.bcrypt.js.git
│ │ https://github.com/ncb000gt/node.bcrypt.js
│ └── bindings@1.0.0
│     Helper module for loading your native module's .node file
│     git://github.com/TooTallNate/node-bindings.git
├─┬ bunyan@0.16.8
│ │ a JSON Logger library for node.js services
│ │ git://github.com/trentm/node-bunyan.git
│ └── dtrace-provider@0.2.4
│     Native DTrace providers for node.js applications
│     http://github.com/chrisa/node-dtrace-provider.git
│     https://github.com/chrisa/node-dtrace-provider#readme
├─┬ connect@1.9.2
│ │ High performance middleware framework
│ │ git://github.com/senchalabs/connect
│ ├── formidable@1.0.17
│ │   A node.js module for parsing form data, especially file uploads.
│ │   git://github.com/felixge/node-formidable.git
│ │   https://github.com/felixge/node-formidable
│ ├── mime@1.3.4
│ │   A comprehensive library for mime-type mapping
│ │   https://github.com/broofa/node-mime
│ └── qs@4.0.0
│     A querystring parser that supports nesting and arrays, with a depth limit
│     git+https://github.com/hapijs/qs.git
│     https://github.com/hapijs/qs
├─┬ connect-auth@0.5.3
│ │ Middleware for Connect (node.js) for handling your authentication needs.
│ │ git://github.com/ciaranj/connect-auth.git
│ ├─┬ connect@2.0.0
│ │ │ High performance middleware framework
│ │ │ git://github.com/senchalabs/connect.git
│ │ ├─┬ debug@2.2.0
│ │ │ │ small debugging utility
│ │ │ │ git://github.com/visionmedia/debug.git
│ │ │ │ https://github.com/visionmedia/debug
│ │ │ └── ms@0.7.1
│ │ │     Tiny ms conversion utility
│ │ │     git://github.com/guille/ms.js.git
│ │ │     https://github.com/guille/ms.js
│ │ ├── formidable@1.0.17
│ │ │   A node.js module for parsing form data, especially file uploads.
│ │ │   git://github.com/felixge/node-formidable.git
│ │ │   https://github.com/felixge/node-formidable
│ │ ├── mime@1.2.4
│ │ │   A comprehensive library for mime-type mapping
│ │ │   git://github.com/bentomas/node-mime.git
│ │ └── qs@0.4.2
│ │     querystring parser
│ │     git://github.com/visionmedia/node-querystring.git
│ ├── oauth@0.9.7
│ │   Library for interacting with OAuth 1.0, 1.0A, 2 and Echo.  Provides simplified client access and allows for construction of more complex apis and OAuth providers.
│ │   git://github.com/ciaranj/node-oauth.git
│ └── openid@0.4.1
│     OpenID 1.1/2.0 library for node.js
│     git://github.com/havard/node-openid.git
├─┬ connect-databank@0.13.0
│ │ Use any databank driver as a store for connect sessions
│ │ https://github.com/evanp/connect-databank.git
│ ├── async@0.2.10
│ │   Higher-order functions and common patterns for asynchronous code
│ │   https://github.com/caolan/async.git
│ │   https://github.com/caolan/async
│ ├── databank@0.19.1
│ │   Abstraction layer for JSON storage
│ │   http://github.com/e14n/databank.git
│ │   http://github.com/e14n/databank
│ ├── node-uuid@1.4.3
│ │   Rigorous implementation of RFC4122 (v1 and v4) UUIDs.
│ │   https://github.com/broofa/node-uuid.git
│ │   https://github.com/broofa/node-uuid
│ ├── set-immediate@0.1.1
│ │   A shim for the setImmediate API
│ │   http://github.com/jussi-kalliokoski/setImmediate.js
│ └── underscore@1.4.4
│     JavaScript's functional programming helper library.
│     git://github.com/documentcloud/underscore.git
│     http://underscorejs.org
├── crypto-cacerts@0.1.0
│   Updates SSL certificate chain to use a directory of certificates.
│   https://github.com/monceaux/crypto-cacerts.git
├─┬ databank@0.19.1
│ │ Abstraction layer for JSON storage
│ │ http://github.com/e14n/databank.git
│ │ http://github.com/e14n/databank
│ ├── set-immediate@0.1.1
│ │   A shim for the setImmediate API
│ │   http://github.com/jussi-kalliokoski/setImmediate.js
│ ├── step@0.0.6
│ │   A simple control-flow library for node.JS that makes parallel execution, serial execution, and error handling painless.
│ │   git+ssh://git@github.com/creationix/step.git
│ │   https://github.com/creationix/step#readme
│ └─┬ vows@0.7.0
│   │ Asynchronous BDD & continuous integration for node.js
│   ├── diff@1.0.8
│   │   A javascript text diff implementation.
│   │   git://github.com/kpdecker/jsdiff.git
│   └── eyes@0.1.8
│       a customizable value inspector
├─┬ dateformat@1.0.11
│ │ A node.js package for Steven Levithan's excellent dateFormat() function.
│ │ https://github.com/felixge/node-dateformat.git
│ │ https://github.com/felixge/node-dateformat
│ ├── get-stdin@4.0.1
│ │   Easier stdin
│ │   https://github.com/sindresorhus/get-stdin
│ │   https://github.com/sindresorhus/get-stdin
│ └─┬ meow@3.3.0
│   │ CLI app helper
│   │ https://github.com/sindresorhus/meow
│   │ https://github.com/sindresorhus/meow
│   ├─┬ camelcase-keys@1.0.0
│   │ │ Convert object keys to camelCase
│   │ │ https://github.com/sindresorhus/camelcase-keys
│   │ │ https://github.com/sindresorhus/camelcase-keys
│   │ ├── camelcase@1.1.0
│   │ │   Convert a dash/dot/underscore/space separated string to camelCase: foo-bar → fooBar
│   │ │   https://github.com/sindresorhus/camelcase
│   │ │   https://github.com/sindresorhus/camelcase
│   │ └── map-obj@1.0.1
│   │     Map object keys and values into a new object
│   │     https://github.com/sindresorhus/map-obj
│   │     https://github.com/sindresorhus/map-obj
│   ├─┬ indent-string@1.2.2
│   │ │ Indent each line in a string
│   │ │ https://github.com/sindresorhus/indent-string
│   │ │ https://github.com/sindresorhus/indent-string
│   │ ├── get-stdin@4.0.1
│   │ │   Easier stdin
│   │ │   https://github.com/sindresorhus/get-stdin
│   │ │   https://github.com/sindresorhus/get-stdin
│   │ ├── minimist@1.1.2
│   │ │   parse argument options
│   │ │   git://github.com/substack/minimist.git
│   │ │   https://github.com/substack/minimist
│   │ └─┬ repeating@1.1.3
│   │   │ Repeat a string - fast
│   │   │ https://github.com/sindresorhus/repeating
│   │   │ https://github.com/sindresorhus/repeating
│   │   └─┬ is-finite@1.0.1
│   │     │ ES6 Number.isFinite() ponyfill
│   │     │ git+https://github.com/sindresorhus/is-finite.git
│   │     │ https://github.com/sindresorhus/is-finite#readme
│   │     └── number-is-nan@1.0.0
│   │         ES6 Number.isNaN() ponyfill
│   │         git+https://github.com/sindresorhus/number-is-nan.git
│   │         https://github.com/sindresorhus/number-is-nan#readme
│   ├── minimist@1.1.2
│   │   parse argument options
│   │   git://github.com/substack/minimist.git
│   │   https://github.com/substack/minimist
│   └── object-assign@3.0.0
│       ES6 Object.assign() ponyfill
│       https://github.com/sindresorhus/object-assign
│       https://github.com/sindresorhus/object-assign
├─┬ dialback-client@0.1.5
│ │ dialback-client ===============
│ │ git://github.com/e14n/dialback-client.git
│ │ http://github.com/e14n/dialback-client
│ ├─┬ databank@0.18.2
│ │ │ Abstraction layer for JSON storage
│ │ │ http://github.com/e14n/databank.git
│ │ │ http://github.com/e14n/databank
│ │ ├── set-immediate@0.1.1
│ │ │   A shim for the setImmediate API
│ │ │   http://github.com/jussi-kalliokoski/setImmediate.js
│ │ ├── step@0.0.6
│ │ │   A simple control-flow library for node.JS that makes parallel execution, serial execution, and error handling painless.
│ │ │   git+ssh://git@github.com/creationix/step.git
│ │ │   https://github.com/creationix/step#readme
│ │ └─┬ vows@0.7.0
│ │   │ Asynchronous BDD & continuous integration for node.js
│ │   ├── diff@1.0.8
│ │   │   A javascript text diff implementation.
│ │   │   git://github.com/kpdecker/jsdiff.git
│ │   └── eyes@0.1.8
│ │       a customizable value inspector
│ ├── express@2.5.11
│ │   Sinatra inspired web development framework
│ │   git://github.com/visionmedia/express
│ ├── step@0.0.6
│ │   A simple control-flow library for node.JS that makes parallel execution, serial execution, and error handling painless.
│ │   git+ssh://git@github.com/creationix/step.git
│ │   https://github.com/creationix/step#readme
│ └── underscore@1.4.4
│     JavaScript's functional programming helper library.
│     git://github.com/documentcloud/underscore.git
│     http://underscorejs.org
├─┬ emailjs@0.3.16
│ │ send text/html emails and attachments (files, streams and strings) from node.js to any smtp server
│ │ http://github.com/eleith/emailjs.git
│ │ https://github.com/eleith/emailjs
│ ├── addressparser@0.3.2
│ │   Parse e-mail addresses
│ │   https://github.com/andris9/addressparser.git
│ │   https://github.com/andris9/addressparser
│ ├── bufferjs@1.1.0
│ │   Pure JavaScript Buffer utils.
│ ├─┬ mimelib@0.2.14
│ │ │ MIME functions to encode/decode e-mails etc.
│ │ │ http://github.com/andris9/mimelib.git
│ │ │ http://github.com/andris9/mimelib
│ │ ├── addressparser@0.2.1
│ │ │   Parse e-mail addresses
│ │ │   https://github.com/andris9/addressparser.git
│ │ │   https://github.com/andris9/addressparser
│ │ └─┬ encoding@0.1.11
│ │   │ Convert encodings, uses iconv by default and fallbacks to iconv-lite if needed
│ │   │ https://github.com/andris9/encoding.git
│ │   │ https://github.com/andris9/encoding
│ │   └── iconv-lite@0.4.11
│ │       Convert character encodings in pure javascript.
│ │       git://github.com/ashtuchkin/iconv-lite.git
│ │       https://github.com/ashtuchkin/iconv-lite
│ ├── moment@1.7.0
│ │   Parse, manipulate, and display dates.
│ │   https://github.com/timrwood/moment.git
│ │   http://momentjs.com
│ └── starttls@0.2.1
│     Upgrade a regular `net.Stream` connection to a secure `tls` connection.
│     https://github.com/mattcg/starttls.git
│     https://github.com/mattcg/starttls
├─┬ express@2.5.11
│ │ Sinatra inspired web development framework
│ │ git://github.com/visionmedia/express
│ ├── connect@1.9.2
│ │   High performance middleware framework
│ │   git://github.com/senchalabs/connect
│ ├── mime@1.2.4
│ │   A comprehensive library for mime-type mapping
│ │   git://github.com/bentomas/node-mime.git
│ ├── mkdirp@0.3.0
│ │   Recursively mkdir, like `mkdir -p`
│ │   git://github.com/substack/node-mkdirp.git
│ └── qs@0.4.2
│     querystring parser
│     git://github.com/visionmedia/node-querystring.git
├─┬ gm@1.9.2
│ │ GraphicsMagick for node.js
│ │ https://github.com/aheckmann/gm.git
│ ├── array-parallel@0.1.3
│ │   Call an array of asynchronous functions in parallel
│ │   https://github.com/component/array-parallel.git
│ │   https://github.com/component/array-parallel
│ ├── array-series@0.1.5
│ │   Call an array of asynchronous functions in series
│ │   https://github.com/component/array-series.git
│ │   https://github.com/component/array-series
│ ├── debug@0.7.0
│ │   small debugging utility
│ ├── stream-to-buffer@0.0.1
│ │   Concatenate a readable stream's data into a single buffer
│ │   https://github.com/jonathanong/stream-to-buffer.git
│ └── through@2.3.8
│     simplified stream construction
│     git+https://github.com/dominictarr/through.git
│     https://github.com/dominictarr/through
├── jankyqueue@0.1.1
│   Knuckle-dragger in-process queuing
│   git://github.com/e14n/jankyqueue.git
│   http://github.com/e14n/jankyqueue
├── mkdirp@0.3.5
│   Recursively mkdir, like `mkdir -p`
│   http://github.com/substack/node-mkdirp.git
├── node-uuid@1.3.3
│   Rigorous implementation of RFC4122 (v1 and v4) UUIDs.
│   git://github.com/broofa/node-uuid.git
├── oauth-evanp@0.9.10-evanp.2
│   Library for interacting with OAuth 1.0, 1.0A, 2 and Echo.  Provides simplified client access and allows for construction of more complex apis and OAuth providers.
│   http://github.com/ciaranj/node-oauth.git
├─┬ optimist@0.3.7
│ │ Light-weight option parsing with an argv hash. No optstrings attached.
│ │ http://github.com/substack/node-optimist.git
│ │ https://github.com/substack/node-optimist
│ └── wordwrap@0.0.3
│     Wrap those words. Show them at what columns to start and stop.
│     git://github.com/substack/node-wordwrap.git
│     https://github.com/substack/node-wordwrap#readme
├── schlock@0.2.1
│   Poorly-crafted in-process lock broker
│   git://github.com/e14n/schlock.git
│   http://github.com/e14n/schlock
├── set-immediate@0.1.1
│   A shim for the setImmediate API
│   http://github.com/jussi-kalliokoski/setImmediate.js
├── showdown@0.3.4
│   A JavaScript port of Markdown
│   https://github.com/showdownjs/showdown.git
│   https://github.com/showdownjs/showdown
├─┬ sockjs@0.3.15
│ │ SockJS-node is a server counterpart of SockJS-client a JavaScript library that provides a WebSocket-like object in the browser. SockJS gives you a coherent, cross-browser, Javascript API which creates a low latency, full duplex, cross-domain communication
│ │ https://github.com/sockjs/sockjs-node.git
│ │ https://github.com/sockjs/sockjs-node
│ ├─┬ faye-websocket@0.9.4
│ │ │ Standards-compliant WebSocket server and client
│ │ │ git://github.com/faye/faye-websocket-node.git
│ │ │ http://github.com/faye/faye-websocket-node
│ │ └─┬ websocket-driver@0.6.2
│ │   │ WebSocket protocol handler with pluggable I/O
│ │   │ git://github.com/faye/websocket-driver-node.git
│ │   │ http://github.com/faye/websocket-driver-node
│ │   └── websocket-extensions@0.1.1
│ │       Generic extension manager for WebSocket connections
│ │       git://github.com/faye/websocket-extensions-node.git
│ │       http://github.com/faye/websocket-extensions-node
│ └── node-uuid@1.4.3
│     Rigorous implementation of RFC4122 (v1 and v4) UUIDs.
│     https://github.com/broofa/node-uuid.git
│     https://github.com/broofa/node-uuid
├── step@0.0.6
│   A simple control-flow library for node.JS that makes parallel execution, serial execution, and error handling painless.
│   git+ssh://git@github.com/creationix/step.git
│   https://github.com/creationix/step#readme
├── underscore@1.4.4
│   JavaScript's functional programming helper library.
│   git://github.com/documentcloud/underscore.git
│   http://underscorejs.org
├─┬ underscore-contrib@0.1.4
 ==================rib
│ │ https://github.com/documentcloud/underscore-contrib.git
│ │ https://github.com/documentcloud/underscore-contrib
│ └── underscore@1.4.4
│     JavaScript's functional programming helper library.
│     git://github.com/documentcloud/underscore.git
│     http://underscorejs.org
├─┬ utml@0.2.0
│ │ Express compliant templating for underscore.js
│ │ git://github.com/mikefrey/utml.git
│ └── underscore@1.4.4
│     JavaScript's functional programming helper library.
│     git://github.com/documentcloud/underscore.git
│     http://underscorejs.org
├── validator@0.4.28
│   Data validation, filtering and sanitization for node.js
│   http://github.com/chriso/node-validator.git
│   http://github.com/chriso/node-validator
└─┬ webfinger@0.4.2
  │ Client library for Host Meta (RFC 6415) and Webfinger
  │ git://github.com/e14n/webfinger.git
  │ http://github.com/e14n/webfinger
  ├── step@0.0.6
  │   A simple control-flow library for node.JS that makes parallel execution, serial execution, and error handling painless.
  │   git+ssh://git@github.com/creationix/step.git
  │   https://github.com/creationix/step#readme
  └─┬ xml2js@0.1.14
    │ Simple XML to JavaScript object converter.
    │ git://github.com/Leonidas-from-XIV/node-xml2js.git
    │ https://github.com/Leonidas-from-XIV/node-xml2js
    └── sax@1.1.1
        An evented streaming XML parser in JavaScript
        git://github.com/isaacs/sax-js.git
        https://github.com/isaacs/sax-js#readme
```

And here's my `databank-mongodb` information:

```
% cd /usr/local/lib/node_modules/databank-mongodb; npm ll
databank-mongodb@0.18.7
│ /usr/local/lib/node_modules/databank-mongodb
│ Databank driver for MongoDB
│ git+ssh://git@github.com/e14n/databank-mongodb.git
│ http://github.com/e14n/databank-mongodb
├─┬ databank@0.19.1
│ │ Abstraction layer for JSON storage
│ │ http://github.com/e14n/databank.git
│ │ http://github.com/e14n/databank
│ ├── set-immediate@0.1.1
│ │   A shim for the setImmediate API
│ │   http://github.com/jussi-kalliokoski/setImmediate.js
│ ├── step@0.0.6
│ │   A simple control-flow library for node.JS that makes parallel execution, serial execution, and error handling painless.
│ │   git+ssh://git@github.com/creationix/step.git
│ │   https://github.com/creationix/step#readme
│ └─┬ vows@0.7.0
│   │ Asynchronous BDD & continuous integration for node.js
│   ├── diff@1.0.8
│   │   A javascript text diff implementation.
│   │   git://github.com/kpdecker/jsdiff.git
│   └── eyes@0.1.8
│       a customizable value inspector
├─┬ mongodb@2.0.39
│ │ MongoDB legacy driver emulation layer on top of mongodb-core
│ │ git@github.com:mongodb/node-mongodb-native.git
│ │ https://github.com/mongodb/node-mongodb-native
│ ├── es6-promise@2.1.1
│ │   A lightweight library that provides tools for organizing asynchronous code
│ │   git://github.com/jakearchibald/ES6-Promises.git
│ │   https://github.com/jakearchibald/ES6-Promises
│ ├─┬ mongodb-core@1.2.6
│ │ │ Core MongoDB driver functionality, no bells and whistles and meant for integration not end applications
│ │ │ git://github.com/christkv/mongodb-core.git
│ │ │ https://github.com/christkv/mongodb-core
│ │ ├── bson@0.4.8
│ │ │   A bson parser for node.js and the browser
│ │ │   git://github.com/mongodb/js-bson.git
│ │ │   https://github.com/mongodb/js-bson
│ │ └─┬ kerberos@0.0.12
│ │   │ Kerberos library for Node.js
│ │   │ https://github.com/christkv/kerberos.git
│ │   │ https://github.com/christkv/kerberos
│ │   └── nan@1.8.4
│ │       Native Abstractions for Node.js: C++ header for Node 0.8->0.12 compatibility
│ │       git://github.com/iojs/nan.git
│ │       https://github.com/iojs/nan#readme
│ └─┬ readable-stream@1.0.31
│   │ Streams2, a user-land copy of the stream library from Node.js v0.10.x
│   │ git://github.com/isaacs/readable-stream
│   │ https://github.com/isaacs/readable-stream
│   ├── core-util-is@1.0.1
│   │   The `util.is*` functions introduced in Node v0.12.
│   │   git://github.com/isaacs/core-util-is
│   │   https://github.com/isaacs/core-util-is
│   ├── inherits@2.0.1
│   │   Browser-friendly inheritance fully compatible with standard node.js inherits()
│   │   git://github.com/isaacs/inherits
│   │   https://github.com/isaacs/inherits
│   ├── isarray@0.0.1
│   │   Array#isArray for older browsers
│   │   git://github.com/juliangruber/isarray.git
│   │   https://github.com/juliangruber/isarray
│   └── string_decoder@0.10.31
│       The string_decoder module from Node core
│       git://github.com/rvagg/string_decoder.git
│       https://github.com/rvagg/string_decoder
├── step@0.0.6
│   A simple control-flow library for node.JS that makes parallel execution, serial execution, and error handling painless.
│   git+ssh://git@github.com/creationix/step.git
│   https://github.com/creationix/step#readme
└── underscore@1.8.3
    JavaScript's functional programming helper library.
    git://github.com/jashkenas/underscore.git
    http://underscorejs.org
```

Finally:

```
% node -v 
v0.10.29
% mongo --version
MongoDB shell version: 2.4.10
```

I'm using a reverse proxy via Apache, but I verified that this issue happens even without the proxy.

**Comment by strugee** [comment]
Here's some additional info about my MongoDB users:

```
% mongo admin -u root -p
MongoDB shell version: 2.4.10
Enter password: 
connecting to: admin
> use pumpio
switched to db pumpio
> show users
{
	"_id" : ObjectId("55b4acef99af146e79a95c77"),
	"user" : "pump.io",
	"pwd" : "bf8ed69cef03f4079a8ec85cd7380ba3",
	"roles" : [
		"readWrite"
	]
}
> 
```

Perhaps the user doesn't have enough rights? There was no documentation on how to set up the MongoDB user, so I gave it what seemed like a reasonable set of roles.

**Comment by evanp** [comment]
Heh. Did you ever get this fixed?
